# This is a basic workflow to help you get started with Actions

name: Cloud-Resume-Frontend-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: List files
      run: |
        ls
    - name: Uploading files to S3
      run: |
          aws s3 sync . s3://rajanpanchal.net --acl public-read
     # Runs a set of commands using the runners shell
    - name: Getting modified files
      uses: jitterbit/get-changed-files@v1 
      id: files
      with:
          format: csv
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Invalidate Cloudfront cache
      run: |
          mapfile -d ',' -t modified_files < <(printf '%s,' '${{ steps.files.outputs.modified }}')
          for file in "${modified_files[@]}"; do
          if [ "${file}" != ".github/workflows/frontend.yml" ]; then
            echo "Uploading file: ${file}."
            aws cloudfront create-invalidation --distribution-id E120QUMB7Q2UYC --paths "/$file"
          fi
          done
